hackoregon/openelections

api/models/readme.md

This is a very very draft cut laying out data models in general, and specificity for top level items including Governments, Settings, User Management and Campaigns delivered for Phase 1 (https://github.com/hackoregon/openelections/milestone/2).
The documentation will start here as a PR, and then fold into the wiki for general consumption/onboarding 
https://github.com/hackoregon/openelections/wiki/Open-Election-Data-Models
Please make comments on the README and tag me with questions. I'll review, update as needed and resolve.
When we arrive at consensus, we'll code these into SQL, and added to the API
If this is your first time reviewing a PR, click the 'Files Changed', and then onto the readme. You can click on a line number on the file and make a comment.

WIP - Adds initial user data models description for postgres GH-24

---

app/package.json
app/src/App.js
app/src/assets/styles/styles.scss
app/stories/index.story.js
app/yarn.lock

Adds global styles setup and integrates with storybook.

GH-144 Setup  global styles and  integrate with storybook

---

app/package.json
app/yarn.lock

Simply adding component library to repo.

GH-145: add component library to repo

---

.gitignore
api/models/entity/Campaign.ts
api/models/entity/Government.ts
api/models/entity/Permission.ts
api/models/entity/User.ts
api/package-lock.json
api/package.json
api/services/campaignService.ts
api/services/governmentService.ts
api/services/userService.ts
api/test/entities/Campaign.spec.ts
api/test/entities/Government.spec.ts
api/test/entities/Permission.spec.ts
api/test/entities/User.spec.ts
api/test/services/campaignServices.spec.ts
api/test/services/governmentServices.spec.ts
api/test/services/userServices.spec.ts
api/yarn.lock
docker-compose-test.yml

- Adds campaign and government models
- Adds new service for createCampaign
- Adds new service for createGovernment
- Adds permissions table and models
- Adds roles for campaignAdmin, governmentAdmin and staff
- Adds new validations and testing
- Adds new tests for users

WIP: adding initial campaign and government  [#154 #155 ]

---

api/package.json
api/services/permissionService.ts
api/test/services/permissionService.spec.ts
api/yarn.lock

Adds new services to the permission model for campaign, staff and government

adds permission services for adding new users [Closes #159]

---

api/package.json
api/services/permissionService.ts
api/test/services/permissionService.spec.ts
api/yarn.lock
docker-compose.yml

Adds JWT token creation for session token generation to be passed to the front end for auth header requests.

adds jwt token creation service [Closes #163]

---

api/models/entity/User.ts
api/package.json
api/services/emailService.ts
api/services/permissionService.ts
api/services/userService.ts
api/test/entities/User.spec.ts
api/test/services/permissionService.spec.ts
api/test/services/userService.spec.ts
api/yarn.lock

- adds accept invitation service

Accept invitation service 172

---

api/models/entity/User.ts
api/package.json
api/services/emailService.ts
api/services/permissionService.ts
api/services/userService.ts
api/test/entities/User.spec.ts
api/test/services/permissionService.spec.ts
api/yarn.lock

- Adds invitation email and invitation codes for new users.
- Adds invitation email for existing users being added to campaign or government

Add invite user service 171

---

api/models/entity/User.ts
api/services/emailService.ts
api/services/permissionService.ts
api/services/userService.ts
api/test/entities/User.spec.ts
api/test/redis.spec.ts
api/test/services/userService.spec.ts

Adds login service that returns a JWT token

Add login service 164

---

api/models/entity/User.ts
api/services/emailService.ts
api/services/permissionService.ts
api/services/userService.ts
api/test/entities/User.spec.ts
api/test/redis.spec.ts
api/test/services/userService.spec.ts

Adds password reset service with email

Add password reset service 173

---

api/services/userService.ts
api/test/services/permissionService.spec.ts
api/test/services/userService.spec.ts

- Adds a passwordUpdate service

adds passwordUpdate service [Finishes #174]

---

api/services/emailService.ts
api/services/userService.ts
api/test/services/userService.spec.ts

Adds resendInvitationAsync service

adds resend email service [Closes #181]

---

api/models/entity/Campaign.ts
api/models/entity/Government.ts
api/models/entity/Permission.ts
api/models/entity/User.ts
api/services/userService.ts
api/test/entities/Permission.spec.ts
api/test/entities/User.spec.ts
api/test/factories.ts
api/test/services/permissionService.spec.ts
api/test/services/userService.spec.ts

- Adds factories for new User, Government and Campaign
- Adds retrieveUsersAsync

adds new factories, retrieveUsersAsync and new test patterns 

---

api/controller/users.ts
api/routes/index.ts
api/test/routes/users/passwordReset.spec.ts

- Adds put /users/password route

adds put /users/password route closes GH-96

---

api/controller/users.ts
api/routes/index.ts
api/test/routes/users/invite.spec.ts

- add /users/redeem-invite route

adds /users/redeem-invite route closes GH-195

---

api/package-lock.json
api/package.json
api/routes/components.yaml
api/routes/index.ts

In Swagger UI, authorize using the login route rather than the Authorize button (see https://github.com/swagger-api/swagger-js/issues/1163).

Add Swagger (OAS 3.0) - GH #108

---

api/models/entity/Activity.ts
api/models/entity/Campaign.ts
api/models/entity/Contribution.ts
api/models/entity/Government.ts
api/test/entities/Contribution.spec.ts

Add a new Contribution entity to the api

adds contribution entity model closes GH-234

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/other-issues.md
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/user-flow-issue.md

Added basic issue templates from Civic and included a flow template.

Add issue templates based on CIVIC repo w/ flow

---

api/controller/contributions.ts
api/models/entity/Contribution.ts
api/models/seeds/index.ts
api/models/seeds/seeds.ts
api/routes/components.yaml
api/routes/index.ts
api/services/contributionService.ts
api/test/entities/Contribution.spec.ts
api/test/factories.ts
api/test/routes/contributions/get.spec.ts
api/test/routes/contributions/new.spec.ts
api/test/routes/contributions/update.spec.ts
api/test/services/contributionService.spec.ts
app/src/api/api.js
app/src/api/schema.js
app/src/state/ducks/contributions.js

Adds routes for put /contributions/:id

Route put contribution gh 238

---

api/Readme.md
api/controller/contributions.ts
api/models/entity/Activity.ts
api/models/entity/Campaign.ts
api/models/entity/Contribution.ts
api/models/entity/Expenditure.ts
api/models/entity/Government.ts
api/routes/components.yaml
api/services/contributionService.ts
api/services/expenditureService.ts
api/test/entities/Contribution.spec.ts
api/test/entities/Expenditure.spec.ts
api/test/factories.ts
api/test/services/contributionService.spec.ts
api/tsconfig.json
api/yarn.lock

Adds an entity model for expenditures

Entity Model for Expenditures

---

README.md

I didn't realize this existed, so adding a link to the README.md at project route

Add wiki to read me

---

.travis.yml
api/.dockerignore
api/Dockerfile.production
api/models/db.ts
api/package.json
api/pm2.json
app/Dockerfile.production
app/nginx.conf
docker-compose-production.yml
docker-compose.yml
scripts/build.sh
scripts/deploy.sh
scripts/ecs-deploy.sh

Adds deploy scripts and updates for production AWS infrastructure

Add deploy scripts

---

api/services/emailService.ts
app/__snapshots__/Pages/SignUp/SignUp.test.js.snap
app/__snapshots__/components/Forms/Signup.test.js.snap
app/src/Pages/Invitation/Invitation.js
app/src/Pages/Invitation/Invitation.test.js
app/src/Pages/Portal/ManagePortal/ManagePortal.js
app/src/Pages/Portal/ManagePortal/index.js
app/src/Pages/SignUp/SignUp.js
app/src/Pages/routes.js
app/src/components/Forms/AddUser/index.js
app/src/components/Forms/SignUp/SignUpForm.js
app/src/components/Forms/SignUp/SignUpForm.test.js
app/src/components/Forms/SignUp/index.js
app/src/components/Invitation/index.js
app/src/components/Table/index.js
app/src/state/ducks/users.js
app/src/state/ducks/users.test.js
app/stories/Invitation.story.js
app/stories/index.story.js

Review and merge #407 first, as this builds off of that.

Finish Add New Campaign User Flow GH-314

---

app/src/App.js
app/src/state/ducks/auth.js

On page/browser refresh, dipsatches me() to add auth to state

loads auth on page refresh closes #428

---

app/src/App.js
app/src/state/ducks/auth.js
app/src/state/ducks/auth.test.js
app/src/state/ducks/campaigns.js
app/src/state/ducks/campaigns.test.js
app/src/state/ducks/governments.js
app/src/state/ducks/governments.test.js

Adds a currentCampaignId to campaigns state
Adds a currentGovernmentId to governments state
This is set on Me request

Set current campaign or government 429

---

app/package.json
app/src/configureStore.js
app/src/index.js
app/yarn.lock

Adds Connected Redux Router to access navigation push in actions, and params in connected components through state.router...

adds connected react router to redux closes #427

---

app/src/App.js
app/src/Pages/Portal/Dashboard/Dashboard.js
app/src/Pages/Portal/Portal.js
app/src/components/Navigation/Navigation.js
app/src/components/Navigation/index.js
app/src/components/TopNavigation/TopNavigation.js
app/src/components/TopNavigation/index.js
app/src/components/WithPermissions/Permissions.js
app/src/components/WithPermissions/index.js
app/src/state/ducks/auth.js

Adds new WithPermissions component that checks loggedin status, and will check route against permissions.

WIP HOC WithPermissions

---

app/src/Pages/Portal/ManagePortal/index.js

Uses state tree for campaign id

replace hardcoded campaign id with state closes #438

---

datascience/Dockerfile.production
datascience/openelections/api/donor_lookup.py
docker-compose-production.yml
scripts/deploy.sh

Adds the DS application to Amazon stack

adds ds application to ecs closes #399

---

api/models/entity/User.ts

Adds additional security for passwords in production mode

increases password security closes 185

---

api/controller/users.ts
api/test/routes/users/login.spec.ts

Adds domain name for cookie token for auth.

fixes cookie issue between subdomains closes #475

---

api/models/entity/User.ts

Updates the validate password methods for production

fixes issue with password validation closes #484

---

app/src/Pages/Portal/ManagePortal/ManagePortal.js

Adds fix for Manage Portal page isLoading logic.

Fix for manage portal

---

api/services/emailService.ts

Fixes the issue with email not having the right link

Fix email password link

---

app/README.md

Removes some old instructions, and updates the current development instructions.

Updating frontend README instructions

---

api/package-lock.json
api/package.json
api/routes/index.ts

Testing if this will pass CI. Passes locally, assuming the bug had to do with our specs file that is now resolved. 
Ran locally:
docker-compose -f docker-compose-test.yml run --rm api npm test

Uncommented swagger lines and is passing tests now

---

app/src/configureStore.js

Adds Contribution reducer to store.

Add Contributions to Redux Store

---

app/__snapshots__/Pages/Portal/Contributions/Contributions.test.js.snap
app/src/Pages/Portal/Contributions/AddContribution/AddContribution.js
app/src/Pages/Portal/Contributions/Contributions.js
app/src/Pages/Portal/Contributions/ContributionsTable/ContributionsTable.js
app/src/Pages/Portal/Contributions/ContributionsTable/ContributionsTable.test.js
app/src/Pages/Portal/Contributions/index.js
app/src/Pages/Portal/ManageCampaign/ManageCampaign.js
app/src/Pages/Portal/ManageCampaign/index.js
app/src/Pages/Portal/Portal.js
app/src/Pages/routes.js
app/src/components/ActivityStream/index.js
app/src/components/Button/Button.js
app/src/components/Form/Form.js
app/src/components/Forms/AddContribution/AddContributionForm.js
app/src/components/Forms/AddContribution/index.js
app/src/components/Sidebar/Sidebar.js
app/src/configureStore.js
app/src/state/ducks/contributions.js

Add links to AddContribution form, and adds in necessary logic and API calls.

WIP: Submit A New Contribution GH #376

---

api/app.ts
app/src/state/ducks/auth.js

Fixes log out for qa and production

Fix logout

---

app/src/components/Forms/AddCampaign/index.js

This issue closes acceptance criteria in #528.

fix spacing between buttons

---

app/src/Pages/ForgotPassword/ForgotPassword.js
app/src/Pages/Portal/ManageCampaign/ManageCampaign.js
app/src/Pages/Portal/Portal.js
app/src/Pages/UpdateForgottenPassword/UpdateForgottenPassword.js
app/src/components/ActivityStream/index.js
app/src/components/Forms/ForgotPassword.js
app/src/components/Sidebar/Sidebar.js
app/src/state/ducks/modal.js

Removes unnecessary calls to console.log. Resolves #538

Removes unnecessary console.logs GH-538

---

app/Dockerfile
app/src/components/FormModal/FormModal.js
app/src/components/Modal/Modal.js
docker-compose-test.yml

Adds scrolling for form modals on small screens. Resolves #526

Enable scrolling on form modals. Resolves #552

---

app/src/Pages/Portal/ManageCampaign/index.js
app/src/components/Forms/AddCampaign/index.js
app/src/components/Sidebar/Sidebar.js
app/src/components/Sidebar/index.js
app/src/state/ducks/auth.js
app/src/state/ducks/governments.js

Fixes Campaigns link does not appear on the right menu at first

---

api/models/entity/Activity.ts
api/services/contributionService.ts
api/test/services/contributionService.spec.ts
docker-compose-test.yml

Add activity record creation to contribution services
